package com.gensi.manage.mapper;

import com.gensi.manage.entity.Gsmanage;
import com.gensi.manage.entity.GsmanageExample;
import com.gensi.manage.entity.GsmanageWithBLOBs;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

@Mapper
public interface GsmanageMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gensi..gsmanage
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    int countByExample(GsmanageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gensi..gsmanage
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    int deleteByExample(GsmanageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gensi..gsmanage
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    int deleteByPrimaryKey(String sysid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gensi..gsmanage
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    int insert(GsmanageWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gensi..gsmanage
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    int insertSelective(GsmanageWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gensi..gsmanage
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    List<GsmanageWithBLOBs> selectByExampleWithBLOBs(GsmanageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gensi..gsmanage
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    List<Gsmanage> selectByExample(GsmanageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gensi..gsmanage
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    GsmanageWithBLOBs selectByPrimaryKey(String sysid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gensi..gsmanage
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    int updateByExampleSelective(@Param("record") GsmanageWithBLOBs record, @Param("example") GsmanageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gensi..gsmanage
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    int updateByExampleWithBLOBs(@Param("record") GsmanageWithBLOBs record, @Param("example") GsmanageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gensi..gsmanage
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    int updateByExample(@Param("record") Gsmanage record, @Param("example") GsmanageExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gensi..gsmanage
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    int updateByPrimaryKeySelective(GsmanageWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gensi..gsmanage
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    int updateByPrimaryKeyWithBLOBs(GsmanageWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gensi..gsmanage
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    int updateByPrimaryKey(Gsmanage record);
}