package com.gensi.manage.entity;

import java.io.Serializable;

public class Gsmanage implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gensi..gsmanage.sysId
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    private String sysid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gensi..gsmanage.sysName
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    private String sysname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gensi..gsmanage.authedIp
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    private String authedip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gensi..gsmanage.userName
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    private String username;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gensi..gsmanage.pwd
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    private String pwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gensi..gsmanage.notifyUrl
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    private String notifyurl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gensi..gsmanage.notifyParam
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    private String notifyparam;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gensi..gsmanage.deleteFlag
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    private String deleteflag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gensi..gsmanage.reserve1
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    private String reserve1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gensi..gsmanage.reserve2
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    private String reserve2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gensi..gsmanage
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gensi..gsmanage.sysId
     *
     * @return the value of gensi..gsmanage.sysId
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    public String getSysid() {
        return sysid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gensi..gsmanage.sysId
     *
     * @param sysid the value for gensi..gsmanage.sysId
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    public void setSysid(String sysid) {
        this.sysid = sysid == null ? null : sysid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gensi..gsmanage.sysName
     *
     * @return the value of gensi..gsmanage.sysName
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    public String getSysname() {
        return sysname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gensi..gsmanage.sysName
     *
     * @param sysname the value for gensi..gsmanage.sysName
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    public void setSysname(String sysname) {
        this.sysname = sysname == null ? null : sysname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gensi..gsmanage.authedIp
     *
     * @return the value of gensi..gsmanage.authedIp
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    public String getAuthedip() {
        return authedip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gensi..gsmanage.authedIp
     *
     * @param authedip the value for gensi..gsmanage.authedIp
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    public void setAuthedip(String authedip) {
        this.authedip = authedip == null ? null : authedip.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gensi..gsmanage.userName
     *
     * @return the value of gensi..gsmanage.userName
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gensi..gsmanage.userName
     *
     * @param username the value for gensi..gsmanage.userName
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    public void setUsername(String username) {
        this.username = username == null ? null : username.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gensi..gsmanage.pwd
     *
     * @return the value of gensi..gsmanage.pwd
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gensi..gsmanage.pwd
     *
     * @param pwd the value for gensi..gsmanage.pwd
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    public void setPwd(String pwd) {
        this.pwd = pwd == null ? null : pwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gensi..gsmanage.notifyUrl
     *
     * @return the value of gensi..gsmanage.notifyUrl
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    public String getNotifyurl() {
        return notifyurl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gensi..gsmanage.notifyUrl
     *
     * @param notifyurl the value for gensi..gsmanage.notifyUrl
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    public void setNotifyurl(String notifyurl) {
        this.notifyurl = notifyurl == null ? null : notifyurl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gensi..gsmanage.notifyParam
     *
     * @return the value of gensi..gsmanage.notifyParam
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    public String getNotifyparam() {
        return notifyparam;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gensi..gsmanage.notifyParam
     *
     * @param notifyparam the value for gensi..gsmanage.notifyParam
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    public void setNotifyparam(String notifyparam) {
        this.notifyparam = notifyparam == null ? null : notifyparam.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gensi..gsmanage.deleteFlag
     *
     * @return the value of gensi..gsmanage.deleteFlag
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    public String getDeleteflag() {
        return deleteflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gensi..gsmanage.deleteFlag
     *
     * @param deleteflag the value for gensi..gsmanage.deleteFlag
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    public void setDeleteflag(String deleteflag) {
        this.deleteflag = deleteflag == null ? null : deleteflag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gensi..gsmanage.reserve1
     *
     * @return the value of gensi..gsmanage.reserve1
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    public String getReserve1() {
        return reserve1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gensi..gsmanage.reserve1
     *
     * @param reserve1 the value for gensi..gsmanage.reserve1
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    public void setReserve1(String reserve1) {
        this.reserve1 = reserve1 == null ? null : reserve1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gensi..gsmanage.reserve2
     *
     * @return the value of gensi..gsmanage.reserve2
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    public String getReserve2() {
        return reserve2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gensi..gsmanage.reserve2
     *
     * @param reserve2 the value for gensi..gsmanage.reserve2
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    public void setReserve2(String reserve2) {
        this.reserve2 = reserve2 == null ? null : reserve2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gensi..gsmanage
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", sysid=").append(sysid);
        sb.append(", sysname=").append(sysname);
        sb.append(", authedip=").append(authedip);
        sb.append(", username=").append(username);
        sb.append(", pwd=").append(pwd);
        sb.append(", notifyurl=").append(notifyurl);
        sb.append(", notifyparam=").append(notifyparam);
        sb.append(", deleteflag=").append(deleteflag);
        sb.append(", reserve1=").append(reserve1);
        sb.append(", reserve2=").append(reserve2);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}