package com.gensi.manage.entity;

import java.io.Serializable;

public class GsmanageWithBLOBs extends com.gensi.manage.entity.Gsmanage implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gensi..gsmanage.privateKey
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    private String privatekey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gensi..gsmanage.publicKey
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    private String publickey;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gensi..gsmanage
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gensi..gsmanage.privateKey
     *
     * @return the value of gensi..gsmanage.privateKey
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    public String getPrivatekey() {
        return privatekey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gensi..gsmanage.privateKey
     *
     * @param privatekey the value for gensi..gsmanage.privateKey
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    public void setPrivatekey(String privatekey) {
        this.privatekey = privatekey == null ? null : privatekey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gensi..gsmanage.publicKey
     *
     * @return the value of gensi..gsmanage.publicKey
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    public String getPublickey() {
        return publickey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gensi..gsmanage.publicKey
     *
     * @param publickey the value for gensi..gsmanage.publicKey
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    public void setPublickey(String publickey) {
        this.publickey = publickey == null ? null : publickey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gensi..gsmanage
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", privatekey=").append(privatekey);
        sb.append(", publickey=").append(publickey);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}