package com.gensi.manage.entity;

import java.io.Serializable;

public class GsrequestKey implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gensi..gsrequest.transId
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    private String transid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gensi..gsrequest.serviceCode
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    private String servicecode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gensi..gsrequest
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gensi..gsrequest.transId
     *
     * @return the value of gensi..gsrequest.transId
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    public String getTransid() {
        return transid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gensi..gsrequest.transId
     *
     * @param transid the value for gensi..gsrequest.transId
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    public void setTransid(String transid) {
        this.transid = transid == null ? null : transid.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gensi..gsrequest.serviceCode
     *
     * @return the value of gensi..gsrequest.serviceCode
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    public String getServicecode() {
        return servicecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gensi..gsrequest.serviceCode
     *
     * @param servicecode the value for gensi..gsrequest.serviceCode
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    public void setServicecode(String servicecode) {
        this.servicecode = servicecode == null ? null : servicecode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gensi..gsrequest
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", transid=").append(transid);
        sb.append(", servicecode=").append(servicecode);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}