package com.gensi.manage.entity;

import java.io.Serializable;

public class GsrequestWithBLOBs extends Gsrequest implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gensi..gsrequest.reqBody
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    private String reqbody;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column gensi..gsrequest.rspBody
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    private String rspbody;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gensi..gsrequest
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gensi..gsrequest.reqBody
     *
     * @return the value of gensi..gsrequest.reqBody
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    public String getReqbody() {
        return reqbody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gensi..gsrequest.reqBody
     *
     * @param reqbody the value for gensi..gsrequest.reqBody
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    public void setReqbody(String reqbody) {
        this.reqbody = reqbody == null ? null : reqbody.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column gensi..gsrequest.rspBody
     *
     * @return the value of gensi..gsrequest.rspBody
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    public String getRspbody() {
        return rspbody;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column gensi..gsrequest.rspBody
     *
     * @param rspbody the value for gensi..gsrequest.rspBody
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    public void setRspbody(String rspbody) {
        this.rspbody = rspbody == null ? null : rspbody.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gensi..gsrequest
     *
     * @mbggenerated Wed Feb 07 17:06:08 CST 2018
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", reqbody=").append(reqbody);
        sb.append(", rspbody=").append(rspbody);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}