package com.gensi.manage.entity;

import java.util.ArrayList;
import java.util.List;

public class GsrequestExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gensi..gsrequest
     *
     * @mbggenerated Wed Feb 07 16:36:30 CST 2018
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gensi..gsrequest
     *
     * @mbggenerated Wed Feb 07 16:36:30 CST 2018
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table gensi..gsrequest
     *
     * @mbggenerated Wed Feb 07 16:36:30 CST 2018
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gensi..gsrequest
     *
     * @mbggenerated Wed Feb 07 16:36:30 CST 2018
     */
    public GsrequestExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gensi..gsrequest
     *
     * @mbggenerated Wed Feb 07 16:36:30 CST 2018
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gensi..gsrequest
     *
     * @mbggenerated Wed Feb 07 16:36:30 CST 2018
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gensi..gsrequest
     *
     * @mbggenerated Wed Feb 07 16:36:30 CST 2018
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gensi..gsrequest
     *
     * @mbggenerated Wed Feb 07 16:36:30 CST 2018
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gensi..gsrequest
     *
     * @mbggenerated Wed Feb 07 16:36:30 CST 2018
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gensi..gsrequest
     *
     * @mbggenerated Wed Feb 07 16:36:30 CST 2018
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gensi..gsrequest
     *
     * @mbggenerated Wed Feb 07 16:36:30 CST 2018
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gensi..gsrequest
     *
     * @mbggenerated Wed Feb 07 16:36:30 CST 2018
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gensi..gsrequest
     *
     * @mbggenerated Wed Feb 07 16:36:30 CST 2018
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table gensi..gsrequest
     *
     * @mbggenerated Wed Feb 07 16:36:30 CST 2018
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gensi..gsrequest
     *
     * @mbggenerated Wed Feb 07 16:36:30 CST 2018
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andTransidIsNull() {
            addCriterion("transId is null");
            return (Criteria) this;
        }

        public Criteria andTransidIsNotNull() {
            addCriterion("transId is not null");
            return (Criteria) this;
        }

        public Criteria andTransidEqualTo(String value) {
            addCriterion("transId =", value, "transid");
            return (Criteria) this;
        }

        public Criteria andTransidNotEqualTo(String value) {
            addCriterion("transId <>", value, "transid");
            return (Criteria) this;
        }

        public Criteria andTransidGreaterThan(String value) {
            addCriterion("transId >", value, "transid");
            return (Criteria) this;
        }

        public Criteria andTransidGreaterThanOrEqualTo(String value) {
            addCriterion("transId >=", value, "transid");
            return (Criteria) this;
        }

        public Criteria andTransidLessThan(String value) {
            addCriterion("transId <", value, "transid");
            return (Criteria) this;
        }

        public Criteria andTransidLessThanOrEqualTo(String value) {
            addCriterion("transId <=", value, "transid");
            return (Criteria) this;
        }

        public Criteria andTransidLike(String value) {
            addCriterion("transId like", value, "transid");
            return (Criteria) this;
        }

        public Criteria andTransidNotLike(String value) {
            addCriterion("transId not like", value, "transid");
            return (Criteria) this;
        }

        public Criteria andTransidIn(List<String> values) {
            addCriterion("transId in", values, "transid");
            return (Criteria) this;
        }

        public Criteria andTransidNotIn(List<String> values) {
            addCriterion("transId not in", values, "transid");
            return (Criteria) this;
        }

        public Criteria andTransidBetween(String value1, String value2) {
            addCriterion("transId between", value1, value2, "transid");
            return (Criteria) this;
        }

        public Criteria andTransidNotBetween(String value1, String value2) {
            addCriterion("transId not between", value1, value2, "transid");
            return (Criteria) this;
        }

        public Criteria andServicecodeIsNull() {
            addCriterion("serviceCode is null");
            return (Criteria) this;
        }

        public Criteria andServicecodeIsNotNull() {
            addCriterion("serviceCode is not null");
            return (Criteria) this;
        }

        public Criteria andServicecodeEqualTo(String value) {
            addCriterion("serviceCode =", value, "servicecode");
            return (Criteria) this;
        }

        public Criteria andServicecodeNotEqualTo(String value) {
            addCriterion("serviceCode <>", value, "servicecode");
            return (Criteria) this;
        }

        public Criteria andServicecodeGreaterThan(String value) {
            addCriterion("serviceCode >", value, "servicecode");
            return (Criteria) this;
        }

        public Criteria andServicecodeGreaterThanOrEqualTo(String value) {
            addCriterion("serviceCode >=", value, "servicecode");
            return (Criteria) this;
        }

        public Criteria andServicecodeLessThan(String value) {
            addCriterion("serviceCode <", value, "servicecode");
            return (Criteria) this;
        }

        public Criteria andServicecodeLessThanOrEqualTo(String value) {
            addCriterion("serviceCode <=", value, "servicecode");
            return (Criteria) this;
        }

        public Criteria andServicecodeLike(String value) {
            addCriterion("serviceCode like", value, "servicecode");
            return (Criteria) this;
        }

        public Criteria andServicecodeNotLike(String value) {
            addCriterion("serviceCode not like", value, "servicecode");
            return (Criteria) this;
        }

        public Criteria andServicecodeIn(List<String> values) {
            addCriterion("serviceCode in", values, "servicecode");
            return (Criteria) this;
        }

        public Criteria andServicecodeNotIn(List<String> values) {
            addCriterion("serviceCode not in", values, "servicecode");
            return (Criteria) this;
        }

        public Criteria andServicecodeBetween(String value1, String value2) {
            addCriterion("serviceCode between", value1, value2, "servicecode");
            return (Criteria) this;
        }

        public Criteria andServicecodeNotBetween(String value1, String value2) {
            addCriterion("serviceCode not between", value1, value2, "servicecode");
            return (Criteria) this;
        }

        public Criteria andIntimeIsNull() {
            addCriterion("intime is null");
            return (Criteria) this;
        }

        public Criteria andIntimeIsNotNull() {
            addCriterion("intime is not null");
            return (Criteria) this;
        }

        public Criteria andIntimeEqualTo(String value) {
            addCriterion("intime =", value, "intime");
            return (Criteria) this;
        }

        public Criteria andIntimeNotEqualTo(String value) {
            addCriterion("intime <>", value, "intime");
            return (Criteria) this;
        }

        public Criteria andIntimeGreaterThan(String value) {
            addCriterion("intime >", value, "intime");
            return (Criteria) this;
        }

        public Criteria andIntimeGreaterThanOrEqualTo(String value) {
            addCriterion("intime >=", value, "intime");
            return (Criteria) this;
        }

        public Criteria andIntimeLessThan(String value) {
            addCriterion("intime <", value, "intime");
            return (Criteria) this;
        }

        public Criteria andIntimeLessThanOrEqualTo(String value) {
            addCriterion("intime <=", value, "intime");
            return (Criteria) this;
        }

        public Criteria andIntimeLike(String value) {
            addCriterion("intime like", value, "intime");
            return (Criteria) this;
        }

        public Criteria andIntimeNotLike(String value) {
            addCriterion("intime not like", value, "intime");
            return (Criteria) this;
        }

        public Criteria andIntimeIn(List<String> values) {
            addCriterion("intime in", values, "intime");
            return (Criteria) this;
        }

        public Criteria andIntimeNotIn(List<String> values) {
            addCriterion("intime not in", values, "intime");
            return (Criteria) this;
        }

        public Criteria andIntimeBetween(String value1, String value2) {
            addCriterion("intime between", value1, value2, "intime");
            return (Criteria) this;
        }

        public Criteria andIntimeNotBetween(String value1, String value2) {
            addCriterion("intime not between", value1, value2, "intime");
            return (Criteria) this;
        }

        public Criteria andRsptimeIsNull() {
            addCriterion("rsptime is null");
            return (Criteria) this;
        }

        public Criteria andRsptimeIsNotNull() {
            addCriterion("rsptime is not null");
            return (Criteria) this;
        }

        public Criteria andRsptimeEqualTo(String value) {
            addCriterion("rsptime =", value, "rsptime");
            return (Criteria) this;
        }

        public Criteria andRsptimeNotEqualTo(String value) {
            addCriterion("rsptime <>", value, "rsptime");
            return (Criteria) this;
        }

        public Criteria andRsptimeGreaterThan(String value) {
            addCriterion("rsptime >", value, "rsptime");
            return (Criteria) this;
        }

        public Criteria andRsptimeGreaterThanOrEqualTo(String value) {
            addCriterion("rsptime >=", value, "rsptime");
            return (Criteria) this;
        }

        public Criteria andRsptimeLessThan(String value) {
            addCriterion("rsptime <", value, "rsptime");
            return (Criteria) this;
        }

        public Criteria andRsptimeLessThanOrEqualTo(String value) {
            addCriterion("rsptime <=", value, "rsptime");
            return (Criteria) this;
        }

        public Criteria andRsptimeLike(String value) {
            addCriterion("rsptime like", value, "rsptime");
            return (Criteria) this;
        }

        public Criteria andRsptimeNotLike(String value) {
            addCriterion("rsptime not like", value, "rsptime");
            return (Criteria) this;
        }

        public Criteria andRsptimeIn(List<String> values) {
            addCriterion("rsptime in", values, "rsptime");
            return (Criteria) this;
        }

        public Criteria andRsptimeNotIn(List<String> values) {
            addCriterion("rsptime not in", values, "rsptime");
            return (Criteria) this;
        }

        public Criteria andRsptimeBetween(String value1, String value2) {
            addCriterion("rsptime between", value1, value2, "rsptime");
            return (Criteria) this;
        }

        public Criteria andRsptimeNotBetween(String value1, String value2) {
            addCriterion("rsptime not between", value1, value2, "rsptime");
            return (Criteria) this;
        }

        public Criteria andSysidIsNull() {
            addCriterion("sysId is null");
            return (Criteria) this;
        }

        public Criteria andSysidIsNotNull() {
            addCriterion("sysId is not null");
            return (Criteria) this;
        }

        public Criteria andSysidEqualTo(String value) {
            addCriterion("sysId =", value, "sysid");
            return (Criteria) this;
        }

        public Criteria andSysidNotEqualTo(String value) {
            addCriterion("sysId <>", value, "sysid");
            return (Criteria) this;
        }

        public Criteria andSysidGreaterThan(String value) {
            addCriterion("sysId >", value, "sysid");
            return (Criteria) this;
        }

        public Criteria andSysidGreaterThanOrEqualTo(String value) {
            addCriterion("sysId >=", value, "sysid");
            return (Criteria) this;
        }

        public Criteria andSysidLessThan(String value) {
            addCriterion("sysId <", value, "sysid");
            return (Criteria) this;
        }

        public Criteria andSysidLessThanOrEqualTo(String value) {
            addCriterion("sysId <=", value, "sysid");
            return (Criteria) this;
        }

        public Criteria andSysidLike(String value) {
            addCriterion("sysId like", value, "sysid");
            return (Criteria) this;
        }

        public Criteria andSysidNotLike(String value) {
            addCriterion("sysId not like", value, "sysid");
            return (Criteria) this;
        }

        public Criteria andSysidIn(List<String> values) {
            addCriterion("sysId in", values, "sysid");
            return (Criteria) this;
        }

        public Criteria andSysidNotIn(List<String> values) {
            addCriterion("sysId not in", values, "sysid");
            return (Criteria) this;
        }

        public Criteria andSysidBetween(String value1, String value2) {
            addCriterion("sysId between", value1, value2, "sysid");
            return (Criteria) this;
        }

        public Criteria andSysidNotBetween(String value1, String value2) {
            addCriterion("sysId not between", value1, value2, "sysid");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gensi..gsrequest
     *
     * @mbggenerated do_not_delete_during_merge Wed Feb 07 16:36:30 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table gensi..gsrequest
     *
     * @mbggenerated Wed Feb 07 16:36:30 CST 2018
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}